PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE PLAYER_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
PASSWORD CHAR(16) NOT NULL,
CITY CHAR(256) NOT NULL,
GENDER INTEGER NOT NULL,
CAC INTEGER NOT NULL,
LANGUAGE INTEGER NOT NULL,
BIRTHDAY INTEGER NOT NULL,
INTELLIGENCE INTEGER NOT NULL,
KINDNESS INTEGER NOT NULL,
LOOKS INTEGER NOT NULL,
C_D INTEGER NOT NULL
);
CREATE TABLE SPLASH_RAW_RANKING_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
INFO_1 INTEGER NOT NULL,
INFO_2 INTEGER NOT NULL,
INFO_3 INTEGER NOT NULL,
INFO_4 INTEGER NOT NULL,
INFO_5 INTEGER NOT NULL,
INFO_6 INTEGER NOT NULL,
CREATED_DATE datetime default current_timestamp
);
CREATE TABLE SOAR_RAW_RANKING_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
INFO_1 INTEGER NOT NULL,
INFO_2 INTEGER NOT NULL,
INFO_3 INTEGER NOT NULL,
INFO_4 INTEGER NOT NULL,
CREATED_DATE datetime default current_timestamp
);
CREATE TABLE BALLBUBBLE_RAW_RANKING_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
INFO_1 INTEGER NOT NULL,
INFO_2 INTEGER NOT NULL,
INFO_3 INTEGER NOT NULL,
INFO_4 INTEGER NOT NULL,
CREATED_DATE datetime default current_timestamp
);
CREATE TABLE DOROBO_RAW_RANKING_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
INFO_1 INTEGER NOT NULL,
INFO_2 INTEGER NOT NULL,
INFO_3 INTEGER NOT NULL,
INFO_4 INTEGER NOT NULL,
CREATED_DATE datetime default current_timestamp
);
CREATE TABLE SOAR_RANKING_DATA(
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
TOTAL_MATCHES INTEGER NOT NULL,
HIGH_SCORE INTEGER NOT NULL,
unique (USERNAME,RANKMODE)
);
CREATE TABLE BALLBUBBLE_RANKING_DATA(
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
TOTAL_BALLS INTEGER NOT NULL,
HIGH_SCORE INTEGER NOT NULL,
TOTAL_MATCHES INTEGER NOT NULL,
TOTAL_WINS INTEGER NOT NULL,
unique (USERNAME,RANKMODE)
);
CREATE TABLE SPLASH_RANKING_DATA(
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
TOTAL_WINS INTEGER NOT NULL,
TOTAL_LOOSE INTEGER NOT NULL,
TOTAL_SUNK INTEGER NOT NULL,
TOTAL_LOST INTEGER NOT NULL,
TOTAL_HIT INTEGER NOT NULL,
TOTAL_SHOT INTEGER NOT NULL,
unique (USERNAME,RANKMODE)
);
CREATE TABLE DOROBO_RANKING_DATA(
USERNAME CHAR(16) NOT NULL,
RANKMODE INTEGER NOT NULL,
TOTAL_MATCHES INTEGER NOT NULL,
HIGH_SCORE INTEGER NOT NULL,
unique (USERNAME,RANKMODE)
);
COMMIT;
